# Right side specific configuration

# Enable nice!view display
CONFIG_ZMK_DISPLAY=y

# Disable idle blanking for testing
# CONFIG_ZMK_DISPLAY_BLANK_ON_IDLE=n

# Nice!View Widget
CONFIG_NICE_VIEW_WIDGET_STATUS=y

# SPI for nice!view
CONFIG_SPI=y
CONFIG_LS0XX=y

# Increase stack size for display
CONFIG_MAIN_STACK_SIZE=2048
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048
